server:
  port: 8005

spring:
  application:
    name: test-other
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848

# 获取配置文件中的list集合
blacklist:
  sqlBlacklist:
    - create
    - alter
    - drop
#  databaseBlackList:
#    - xxfp
#    - xxfp_mx
#    - xxfp_xhqd
  databaseBlackList: xxfp,xxfp_mx,xxfp_xhqd

#Scheduled定时设置，从前到后依次为 秒 分 时 日 月 周 其中？表示不关心周
#每5分钟间隔
deleteTime: 0 /5 * * * ?